////

|metadata|
{
    "name": "chart-treemap-chart-specific-properties",
    "controlName": ["{WawChartName}"],
    "tags": [],
    "guid": "{015334D6-6D7B-4822-B0EE-A8347189F72D}",  
    "buildFlags": [],
    "createdOn": "2008-05-05T15:00:09Z"
}
|metadata|
////

= Treemap Chart-Specific Properties

The following is a list of methods specific to treemap charts:

pick:[asp-net=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~addcolorinterval.html[UltraChart.TreeMapChart.AddColorInterval]"]  pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~addcolorinterval.html[UltraChart.TreeMapChart.AddColorInterval]"]  pick:[aspnet-old=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~addcolorinterval.html[UltraChart.TreeMapChart.AddColorInterval]"]

pick:[asp-net=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~addcolorvalue.html[UltraChart.TreeMapChart.AddColorValue]"]  pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~addcolorvalue.html[UltraChart.TreeMapChart.AddColorValue]"]  pick:[aspnet-old=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~addcolorvalue.html[UltraChart.TreeMapChart.AddColorValue]"]

The following is a list of properties specific to treemap charts:

pick:[asp-net=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~bordercolor.html[UltraChart.TreeMapChart.BorderColor]"]  pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~bordercolor.html[UltraChart.TreeMapChart.BorderColor]"]  pick:[aspnet-old=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~bordercolor.html[UltraChart.TreeMapChart.BorderColor]"]

pick:[asp-net=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~borderwidth.html[UltraChart.TreeMapChart.BorderWidth]"]  pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~borderwidth.html[UltraChart.TreeMapChart.BorderWidth]"]  pick:[aspnet-old=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~borderwidth.html[UltraChart.TreeMapChart.BorderWidth]"]

pick:[asp-net=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~charttitle.html[UltraChart.TreeMapChart.ChartTitle]"]  pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~charttitle.html[UltraChart.TreeMapChart.ChartTitle]"]  pick:[aspnet-old=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~charttitle.html[UltraChart.TreeMapChart.ChartTitle]"]

pick:[asp-net=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~clearcolorintervals.html[UltraChart.TreeMapChart.ClearColorIntervals]"]  pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~clearcolorintervals.html[UltraChart.TreeMapChart.ClearColorIntervals]"]  pick:[aspnet-old=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~clearcolorintervals.html[UltraChart.TreeMapChart.ClearColorIntervals]"]

pick:[asp-net=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~colorvalueindex.html[UltraChart.TreeMapChart.ColorValueIndex]"]  pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~colorvalueindex.html[UltraChart.TreeMapChart.ColorValueIndex]"]  pick:[aspnet-old=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~colorvalueindex.html[UltraChart.TreeMapChart.ColorValueIndex]"]

pick:[asp-net=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~colorvaluelabel.html[UltraChart.TreeMapChart.ColorValueLabel]"]  pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~colorvaluelabel.html[UltraChart.TreeMapChart.ColorValueLabel]"]  pick:[aspnet-old=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~colorvaluelabel.html[UltraChart.TreeMapChart.ColorValueLabel]"]

pick:[asp-net=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~disablecolorvalues.html[UltraChart.TreeMapChart.DisableColorValues]"]  pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~disablecolorvalues.html[UltraChart.TreeMapChart.DisableColorValues]"]  pick:[aspnet-old=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~disablecolorvalues.html[UltraChart.TreeMapChart.DisableColorValues]"]

pick:[asp-net=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~indexorder.html[UltraChart.TreeMapChart.IndexOrder]"]  pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~indexorder.html[UltraChart.TreeMapChart.IndexOrder]"]  pick:[aspnet-old=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~indexorder.html[UltraChart.TreeMapChart.IndexOrder]"]

pick:[asp-net=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~margin.html[UltraChart.TreeMapChart.Margin]"]  pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~margin.html[UltraChart.TreeMapChart.Margin]"]  pick:[aspnet-old=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~margin.html[UltraChart.TreeMapChart.Margin]"]

pick:[asp-net=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~pes.html[UltraChart.TreeMapChart.PE]"]  pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~pes.html[UltraChart.TreeMapChart.PE]"]  pick:[aspnet-old=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~pes.html[UltraChart.TreeMapChart.PE]"]

pick:[asp-net=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~rotation.html[UltraChart.TreeMapChart.Rotation]"]  pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~rotation.html[UltraChart.TreeMapChart.Rotation]"]  pick:[aspnet-old=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~rotation.html[UltraChart.TreeMapChart.Rotation]"]

pick:[asp-net=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~showcolorintervalaxis.html[UltraChart.TreeMapChart.ShowColorIntervalAxis]"]  pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~showcolorintervalaxis.html[UltraChart.TreeMapChart.ShowColorIntervalAxis]"]  pick:[aspnet-old=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~showcolorintervalaxis.html[UltraChart.TreeMapChart.ShowColorIntervalAxis]"]

pick:[asp-net=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~showlabels.html[UltraChart.TreeMapChart.ShowLabels]"]  pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~showlabels.html[UltraChart.TreeMapChart.ShowLabels]"]  pick:[aspnet-old=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~showlabels.html[UltraChart.TreeMapChart.ShowLabels]"]

pick:[asp-net=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~sizevalueindex.html[UltraChart.TreeMapChart.SizeValueIndex]"]  pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~sizevalueindex.html[UltraChart.TreeMapChart.SizeValueIndex]"]  pick:[aspnet-old=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~sizevalueindex.html[UltraChart.TreeMapChart.SizeValueIndex]"]

pick:[asp-net=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~sizevaluelabel.html[UltraChart.TreeMapChart.SizeValueLabel]"]  pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~sizevaluelabel.html[UltraChart.TreeMapChart.SizeValueLabel]"]  pick:[aspnet-old=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~sizevaluelabel.html[UltraChart.TreeMapChart.SizeValueLabel]"]

pick:[asp-net=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~staticleafpe.html[UltraChart.TreeMapChart.StaticLeafPE]"]  pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~staticleafpe.html[UltraChart.TreeMapChart.StaticLeafPE]"]  pick:[aspnet-old=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~staticleafpe.html[UltraChart.TreeMapChart.StaticLeafPE]"]

pick:[asp-net=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~treemaptype.html[UltraChart.TreeMapChart.TreeMapType]"]  pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~treemaptype.html[UltraChart.TreeMapChart.TreeMapType]"]  pick:[aspnet-old=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~treemaptype.html[UltraChart.TreeMapChart.TreeMapType]"]

pick:[asp-net=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~usestaticleafpe.html[UltraChart.TreeMapChart.UseStaticLeafPE]"]  pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~usestaticleafpe.html[UltraChart.TreeMapChart.UseStaticLeafPE]"]  pick:[aspnet-old=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.treemapchartappearance~usestaticleafpe.html[UltraChart.TreeMapChart.UseStaticLeafPE]"]