////

|metadata|
{
    "name": "chart-render-charts-using-the-paint-element",
    "controlName": ["{WawChartName}"],
    "tags": [],
    "guid": "{8811E214-DACC-4A8E-8122-2856420CC716}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Render Charts Using the Paint Element

This section explains the applications of the  pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.paintelement.html[PaintElement]"]  pick:[asp-net=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.paintelement.html[PaintElement]"]  pick:[aspnet-old=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.paintelement.html[PaintElement]"]  (PE property) exposed by graphical chart elements ( pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.core.primitives.primitive.html[Primitives]"]  pick:[asp-net=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.core.primitives.primitive.html[Primitives]"]  pick:[aspnet-old=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.core.primitives.primitive.html[Primitives]"] ) and chart Appearances. The Paint Element gives developers a sophisticated degree of control over rendering these objects. It contains properties that govern how elements of the chart are filled and how these elements should be outlined.

Click the links below to find out how you can...

* link:chart-apply-a-gradient-effect-to-a-primitive.html[Apply a Gradient Effect to a Primitive]
* link:chart-apply-a-hatch-style-to-a-primitive.html[Apply a Hatch Style to a Primitive]
* link:chart-apply-a-texture-effect-to-a-primitive.html[Apply a Texture Effect to a Primitive]
* link:chart-apply-an-image-to-a-chart-primitive.html[Apply an Image to a Chart Primitive]
* link:chart-customize-the-appearance-of-a-charts-background.html[Customize the Appearance of a Chart's Background]
* link:chart-set-the-opacity-of-a-gradient-effect.html[Set the Opacity of the Gradient]
* link:chart-use-a-custom-brush-in-a-paintelement.html[Use a Custom Brush in a PaintElement]
* link:chart-use-the-paintelements-elementtype-property.html[Use the PaintElement's ElementType Property]
* link:chart-use-the-paintelements-fill-stroke-and-strokewidth-properties.html[Use the PaintElement's Fill, Stroke, and StrokeWidth Properties]