////

|metadata|
{
    "name": "chart-specify-row-labels",
    "controlName": ["{WawChartName}"],
    "tags": [],
    "guid": "{866DF402-1BF7-417D-8C45-73218ECB701D}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Specify Row Labels

Many chart types support automatic series labeling based on the first string column that is projected in a row. If another column specifies the desired series labels, then a row labels column can be specified. This topic describes how you can select row labels other than the default ones determined by the chart type.

This topic describes how the row labels can be taken from a specified column in the data source. By default, the row labels are read from the first column in the table that contains a string. To override this, the  pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.dataappearance~userowlabelscolumn.html[UseRowLabelsColumn]"]  pick:[asp-net=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.dataappearance~userowlabelscolumn.html[UseRowLabelsColumn]"]  pick:[aspnet-old=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.dataappearance~userowlabelscolumn.html[UseRowLabelsColumn]"]  property will need to be set to True. Then the  pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.dataappearance~rowlabelscolumn.html[RowLabelsColumn]"]  pick:[asp-net=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.dataappearance~rowlabelscolumn.html[RowLabelsColumn]"]  pick:[aspnet-old=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.dataappearance~rowlabelscolumn.html[RowLabelsColumn]"]  property can be set to the column number in that data source that contains the row labels.

Enter the following code to specify the column to use for row labels:

*In Visual Basic:*

----
Private Sub Specify_Row_Labels_Load(ByVal sender As System.Object, _
  ByVal e As System.EventArgs) Handles MyBase.Load
	Me.UltraChart1.Data.UseRowLabelsColumn = True
	Me.UltraChart1.Data.RowLabelsColumn = 3
End Sub
----

*In C#:*

----
private void Specify_Row_Labels_Load(object sender, EventArgs e)
{
	this.ultraChart1.Data.UseRowLabelsColumn = true;
	this.ultraChart1.Data.RowLabelsColumn = 3;
}
----