////

|metadata|
{
    "name": "chart-deploying-winchart",
    "controlName": ["{WawChartName}"],
    "tags": [],
    "guid": "{8585023D-00A1-4E4A-B0ED-30362DE3DB06}",  
    "buildFlags": ["win-forms","win-forms-old"],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Deploying WinChart

When deploying a .NET application, you must distribute certain files in addition to your executable. If your application contains one or more Infragistics elements, you will have to distribute or deploy one or more Infragistics assembly files as part of your application. This topic outlines the files that you must re-distribute.

.Note
[NOTE]
====
Any files not specifically covered by this topic should be considered non-redistributable. Files that are included with your Infragistics product but not listed here are not licensed for distribution, and should not be copied to, moved to or shared with any machine other than the one on which the licensed Infragistics product is installed.
====

In order to deploy your application, you will have to re-distribute the following files.

[options="header", cols="a,a"]
|====
|File Name|Description

|Infragistics4.Win.UltraWinChart.v{ProductVersion}.dll
|$$.NET$$ Assembly containing all the WinChart™ control.

|====