////

|metadata|
{
    "name": "chart-exporting-to-pdf",
    "controlName": ["{WawChartName}"],
    "tags": [],
    "guid": "{6EC7E9F9-E4FD-4D8F-B650-81A7D3C64997}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Exporting to PDF

This feature allows you to export your chart to either a Portable Document Format (PDF) file or an XML Paper Specification (XPS) file in only a few lines of code.

Exporting your chart to PDF works in conjunction with the Document Engine. For more information on the Document Engine, see  pick:[win-forms,win-forms-old=" link:waw-infragistics-document-engine.html[Infragistics Document Engine]"]  pick:[asp-net,aspnet-old=" link:waw-infragistics-document-engine.html[Infragistics Document Engine]"] .

A public method  pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.win.ultrawinchart.ultrachart~renderpdffriendlygraphics.html[RenderPdfFriendlyGraphics]"]  pick:[asp-net=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.webui.ultrawebchart.ultrachart~renderpdffriendlygraphics.html[RenderPdfFriendlyGraphics]"]  pick:[aspnet-old=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.webui.ultrawebchart.ultrachart~renderpdffriendlygraphics.html[RenderPdfFriendlyGraphics]"]  is exposed which accepts a System.Drawing.Graphics object.

An overload of the RenderPdfFriendlyGraphics method is also available which accepts a System.Drawing.Graphics.object as well as a pixel width and height. If your chart's dimensions are too large to fit into a PDF document's canvas, then the rendered image will be scaled down based on the specified size to chart size ratio.

You must create a Report with a Canvas element, then call the CreateGraphics method on your Canvas element to pass the graphics object to the chart's renderer.

You have to create the Report manually because the chart does not automatically include the Infragistics.Documents assembly, which is required for working with PDF files.

This assembly is not a part of the chart, otherwise you would have an extra assembly included at all times, even if you were not using the exporting to PDF functionality.

== Related Topics

link:chart-export-to-pdf.html[Export to PDF]

link:chart-exporting-numerous-charts-to-a-pdf.html[Exporting Numerous Charts to a PDF]