////

|metadata|
{
    "name": "chart-charts-event-model",
    "controlName": ["{WawChartName}"],
    "tags": [],
    "guid": "{AB604742-1025-4C5E-AE6A-8F3C6BA6EA27}",  
    "buildFlags": [],
    "createdOn": "2008-05-12T10:20:16Z"
}
|metadata|
////

= Chart's Event Model

The Chart control offers many events that you can handle to achieve any kind of programming logic to solve most business problems. Knowing what events Chart has to offer can make programming much simpler and easier to maintain.

In order to handle these events, you will need to understand the basics of Chart's object model. Many of Chart's objects are presented to you through the Event Arguments that you can access in the event handlers. With the abundance of available events, there is no reason why any kind of complex business logic cannot be implemented one way or another.

In this section, you will learn about several useful events that you can use to achieve basic functionaility that you will find in many applications.

Click the links below to learn more about a few of the most commonly used events in Chart and examples of how to use them.

* link:chart-chartdrawitem-event.html[ChartDrawItem Event]
* link:chart-event-model-click-events.html[Click Events]
* link:chart-fillscenegraph-event.html[FillSceneGraph Event]
* link:chart-access-axis-inside-fillscenegraph-event-of-a-composite-chart.html[Access Axis Inside FillSceneGraphEvent of a Composite Chart]
* link:chart-access-axis-inside-fillscenegraph-event-of-a-non-composite-chart.html[Access Axis Inside FillSceneGraphEvent of a Non-Composite Chart]
* link:chart-modify-scene-graph-using-fillscenegraph-event.html[Modify Scene Graph Using FillSceneGraph Event]

ifdef::win-forms-old,win-forms[]
* link:chart-determine-which-axis-is-being-scrolled-or-scaled.html[Determine Which Axis is Being Scrolled or Scaled]

endif::win-forms-old,win-forms[]

ifdef::aspnet-old,asp-net[]
* link:chart-client-side-events.html[Client-Side Events]

endif::aspnet-old,asp-net[]