////

|metadata|
{
    "name": "chart-webchart-csom-overview",
    "controlName": ["{WawChartName}"],
    "tags": [],
    "guid": "{C3B25DF6-FD52-49FA-940C-2AD37501F187}",  
    "buildFlags": ["asp-net","aspnet-old"],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= CSOM Overview

WebChart™ exposes a robust object model within the client-side JavaScript programming environment. The client-side object model (CSOM) consists of full-fledged JavaScript events that enable developers to program significant units of functionality pertaining to the WebChart control without the need for server-side postbacks.

In general, the object model is derived directly from the object model as it exists on the server. The property names, events, parameters and return values have very similar meanings to their counterparts on the server. However, where noted, properties are sometimes read-only on the client. These properties are only for informational purposes you should not modify them.

The following are links to the CSOM reference information for the WebChart control:

link:webchart-client-side-events-csom.html[Client-Side Events]