////

|metadata|
{
    "name": "chart-layers",
    "controlName": ["{WawChartName}"],
    "tags": [],
    "guid": "{B2A15EA5-DE9D-4A9A-9547-EB67438C5E6F}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Layers

The topics in this section provide you with detailed information about custom layers, and how they can be defined to give you more flexibility with the type of chart that you are rendering. This section also provides you with access to task-based procedures and tutorials related to chart layering.

* link:chart-about-custom-layers.html[About Custom Layers]
* link:chart-adding-custom-layers.html[Adding Custom Layers]
* link:chart-adding-primitives-to-a-chart-layer.html[Adding Primitives to a Chart Layer]
* link:chart-customize-the-appearance-of-a-charts-background.html[Customize the Appearance of a Chart's Background]
* link:chart-implementing-a-custom-layer.html[Implementing a Custom Layer]

ifdef::aspnet-old,asp-net[]
* link:chart-chartdrawitem-event.html[Implement the Chart DrawItem Event]

endif::aspnet-old,asp-net[]

* link:chart-writing-a-layer-class.html[Writing a Layer Class]