////

|metadata|
{
    "name": "chart-creating-a-drilldown-chart-part-1-of-5",
    "controlName": ["{WawChartName}"],
    "tags": [],
    "guid": "{592BE757-3F26-4296-8BE5-A2AC0E1A9754}",  
    "buildFlags": ["win-forms","win-forms-old"],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Creating a Drilldown Chart (Part 1 of 5)

Before we begin, there are several rules that we will establish for this walkthrough.

*Finite Drill Levels*

There are three levels of drilling:

* Level 1 -- represents the Customer entity.
* Level 2 -- represents the Order entity.
* Level 3 -- represents the Order Detail entity.

The data will be retrieved from the Northwind Database located on an instance of SQL Server.

*Drill Path*

When drilling down into the levels, you are limited to drilling in sequence. However, when drilling back up you can skip levels.

For example, you have to drill down from Customers to Orders to Order Details. When drilling back up you can skip from Order Details to Customers. This is because to drill down to Order Details you will need to know the Customer ID and the Order ID of the Order Details you want to display. When drilling up you can skip from Order Details to Customers because the Customer ID is already known.

== Related Topic

link:chart-creating-a-drilldown-chart-part-2-of-5).html[Creating a Drilldown Chart (Part 2 of 5)]