////

|metadata|
{
    "name": "chart-winchart-api-overview",
    "controlName": ["{WawChartName}"],
    "tags": [],
    "guid": "{012AA042-E1A0-43E0-98A3-4417ED6E1ACB}",  
    "buildFlags": ["win-forms","win-forms-old"],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= API Overview

This section lists each namespace that is relevant to the WinChart™ control. We also give you several key classes that you will be using while programming with this control. The namespaces and classes on this page link directly into the "API Reference Guide" section of the help.

[cols="a,a"]
|====
|*WinChart Namespace:* 

pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.win.ultrawinchart_namespace.html[Infragistics.Win.UltraWinChart]"]
|*KeyClasses:* 

pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.win.ultrawinchart.ultrachart.html[UltraChart]"]

|*Core Namespace:* 

pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.core_namespace.html[Infragistics.UltraChart.Core]"]
|*Key Classes and Interface:* 

pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.core.chartcore.html[ChartCore]"] 

pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.core.scenegraph.html[SceneGraph]"] 

pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.core.iadvanceaxis.html[IAdvanceAxis]"]

|*Layers Namespace:* 

pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.core.layers_namespace.html[Infragistics.UltraChart.Core.Layers]"]
|*Key Interface:* 

pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.core.layers.ilayer.html[ILayer interface]"]

|*Primitives Namespace:* 

pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.core.primitives_namespace.html[Infragistics.UltraChart.Core.Primitives]"]
|*Key Class:* 

pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.core.primitives.primitive.html[Primitive]"]

|*Util Namespace:* 

pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.core.util_namespace.html[Infragistics.UltraChart.Core.Util]"]
|*Key Classes:* 

pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.core.util.labelformatter.html[LabelFormatter]"] 

pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.core.util.platform.html[Platform]"]

|*Data Namespace:* 

pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.data_namespace.html[Infragistics.UltraChart.Data]"]
|*Key Classes:* 

pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.data.demotable.html[DemoTable]"] 

pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.data.ganttdatasource.html[GanttDataSource]"]

|*Resources Namespace:* 

pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources_namespace.html[Infragistics.UltraChart.Resources]"]
|*Key Interfaces:* 

pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.ichartcomponent.html[IChartComponent]"] 

pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.irenderlabel.html[IRenderLabel]"]

|*Appearance Namespace:* 

pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance_namespace.html[Infragistics.UltraChart.Resources.Appearance]"]
|*Key Classes:* 

pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.annotation.html[Annotation]"] 

pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.effect.html[Effect]"] 

pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.paintelement.html[PaintElement]"]

|*Events Namespace:* 

pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.shared.events_namespace.html[Infragistics.UltraChart.Shared.Events]"]
|*Key Classes:* 

pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.shared.events.chartdataeventargs.html[ChartDataEventArgs]"] 

pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.shared.events.chartdatainvalideventargs.html[ChartDataInvalidEventArgs]"] 

pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.shared.events.chartdrawitemeventargs.html[ChartDrawItemEventArgs]"]

|*Styles Namespace:* 

pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.shared.styles_namespace.html[Infragistics.UltraChart.Shared.Styles]"]
|*Key Classes and Enumeration:* 

pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.shared.styles.labelstyle.html[LabelStyle]"] 

pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.shared.styles.linestyle.html[LineStyle]"] 

pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.shared.styles.charttype.html[ChartType Enumeration]"]

|====