////

|metadata|
{
    "name": "chart-series-collection",
    "controlName": ["{WawChartName}"],
    "tags": [],
    "guid": "{B15FB09B-5B62-4848-BE13-506E97102FF2}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Series Collection

The  pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.data.series.seriescollection.html[SeriesCollection]"]  pick:[asp-net=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.data.series.seriescollection.html[SeriesCollection]"]  pick:[aspnet-old=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.data.series.seriescollection.html[SeriesCollection]"]  class is provided as a data source for the Chart control. This data source can be easily accessed at design time and run time. The series collection can contain one or more Series objects that are strongly typed and represent different structures of data that meet the requirements of different chart types.

The composite  pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.win.ultrawinchart.ultrachart~charttype.html[ChartType]"]  pick:[asp-net=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.webui.ultrawebchart.ultrachart~charttype.html[ChartType]"]  pick:[aspnet-old=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.shared.styles.charttype.html[ChartType]"]  uses only the SeriesCollection as its data source. For other chart types, the series collection will be used if the Data. pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.win.ultrawinchart.ultrachart~datasource.html[DataSource]"]  pick:[asp-net=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.webui.ultrawebchart.ultrachart~datasource.html[DataSource]"]  pick:[aspnet-old=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.webui.ultrawebchart.ultrachart~datasource.html[DataSource]"]  property is not set.

Each series has a collection of DataPoints called "Points". This collection can be populated or modified at design time or run time. It has a property called "Data", which contains its own DataSource property. This property can be set to a DataTable. Additionally, there are properties that allow you to specify the columns from which data should be retrieved. These "Column" properties vary by type, therefore, you should refer the "API Reference Guide" section of the help for the type of series that you are using.

== Related Topics

link:chart-creating-a-composite-chart-in-code-part-1-of-2.html[Creating a Composite Chart in Code (Part 1 of 2)]

link:chart-requirements-for-series-binding.html[Requirements for Series Binding]

link:chart-axis-requirements-for-composite-charts.html[Axis Requirements for Composite Charts]