////

|metadata|
{
    "name": "chart-setting-a-treemap-charts-colors",
    "controlName": ["{WawChartName}"],
    "tags": [],
    "guid": "{12334EAD-22C3-44E3-A3E6-365F58F3446C}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Setting a Treemap Chart's Colors

Setting the node's colors of your treemap chart is an important part of designing your treemap chart as it can alert your end users to changes over time. It can also help your end users to identify clusters of particularly significant data.

For example, if your treemap chart mapped financial stocks where green shows an increase in stock prices and red shows a decrease in stock prices. Your end user will notice immediately which stocks are rising and which ones are falling.

Click the following link to learn more about setting your treemap chart's colors.

* link:chart-set-a-treemap-charts-color-based-on-hierarchical-level.html[Set a Treemap Chart's Color Based on Hierarchical Level]

Depending on which data source you are using, setting the color of the leaf nodes differs slightly. Click the following links to learn how to set a leaf node's color using different data sources.

* link:chart-map-a-leaf-nodes-color-to-a-specific-column-in-a-data-table.html[Map a Leaf Node's Color to a Specific Column in a DataTable]
* link:chart-set-a-leaf-nodes-color-using-a-treemapseries-object.html[Set a Leaf Node's Color using a TreeMapSeries Object]