////

|metadata|
{
    "name": "chart-connect-scatter-chart-points-with-a-line",
    "controlName": ["{WawChartName}"],
    "tags": [],
    "guid": "{920E88CF-861B-44F9-B684-70FA8A4BA44A}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Connect Scatter Chart Points with a Line

This topic explains how to connect the points in a link:chart-scatter-chart.html[scatter chart] with a line. A line can help users to more easily visualize the differences between data points on the chart.

To create a line that connects the points on a scatter chart, you simply change the  pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.scatterchartappearance~connectwithlines.html[ConnectWithLines]"]  pick:[asp-net=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.scatterchartappearance~connectwithlines.html[ConnectWithLines]"]  pick:[aspnet-old=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.scatterchartappearance~connectwithlines.html[ConnectWithLines]"]  property of the scatter chart to True.

*In Visual Basic:*

----
Me.UltraChart1.ScatterChart.ConnectWithLines = True
----

*In C#:*

----
this.ultraChart1.ScatterChart.ConnectWithLines = true;
----

This code will connect the points in your scatter chart with a line that starts at the first point and connects the points in order, ending with the last one. Setting this property to True makes the connecting line appear, setting it to False makes it disappear.

== Related Topic

link:chart-change-icons-in-a-scatter-chart.html[Change Icons in a Scatter Chart]