////

|metadata|
{
    "name": "chart-change-icons-in-a-scatter-chart",
    "controlName": ["{WawChartName}"],
    "tags": [],
    "guid": "{3AB83E0B-C055-4BFB-A7D8-EDD642EC168E}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Change Icons in a Scatter Chart

This topic will explain how to change the icons displayed in a link:chart-scatter-chart.html[scatter chart]. The chart contains seven built-in icons that can be displayed. They are Plus, X, Triangle, Square, Circle, Diamond, and Upside Down Triangle. You determine which one will be displayed by setting the  pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.scatterchartappearance~icon.html[Icon]"]  pick:[asp-net=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.scatterchartappearance~icon.html[Icon]"]  pick:[aspnet-old=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.ultrachart.resources.appearance.scatterchartappearance~icon.html[Icon]"]  property.

[start=1]
. Before you start writing any code, you should place using/import directives in your code-behind so you don't need to always type out a member's fully qualified name.

*In Visual Basic:*

----
Imports Infragistics.UltraChart.Shared.Styles
----

*In C#:*

----
using Infragistics.UltraChart.Shared.Styles;
----

[start=2]
. To change the icon used in the Scatter chart to a diamond, enter the following code:

*In Visual Basic:*

----
Me.UltraChart1.ScatterChart.Icon = SymbolIcon.Diamond
----

*In C#:*

----
this.ultraChart1.ScatterChart.Icon = SymbolIcon.Diamond;
----

[start=3]
. In addition to the built-in icons, a custom character can also be displayed. The Icon property will need to be set to 'Character' and then the Character property should be set to the character that will be displayed in the chart. This can be a letter, a number or any other symbol on the keyboard.

*In Visual Basic:*

----
Me.UltraChart1.ScatterChart.Icon = SymbolIcon.Character
Me.UltraChart1.ScatterChart.Character = "@"
----

*In C#:*

----
this.ultraChart1.ScatterChart.Icon = SymbolIcon.Character;
this.ultraChart1.ScatterChart.Character = '@';
----

== Related Topic

link:chart-connect-scatter-chart-points-with-a-line.html[Connect Scatter Chart Points with a Line] link:chart-axis-requirements-for-composite-charts.html[]