////

|metadata|
{
    "name": "chart-data-sources-non-series-binding",
    "controlName": ["{WawChartName}"],
    "tags": [],
    "guid": "{95221DE6-9D88-4B4C-852D-1A20991EFB82}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Data Sources (Non-Series Binding)

Throughout the Chart help, chart data is typically described as rows and columns; however, the Chart control is not limited to binding to DataTables. In many applications, other data sources are used, therefore, it is inconvenient to create a DataTable object only for the purposes of Chart.

For this reason, the  pick:[win-forms=" link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.resources.appearance.dataappearance~datasource.html[UltraChart.DataSource]"]   pick:[asp-net=" link:{ApiPlatform}webui.ultrawebchart{ApiVersion}~infragistics.webui.ultrawebchart.ultrachart~datasource.html[UltraChart.DataSource]"]  property supports a wide variety of data source types, including the following:

* link:chart-bind-a-treemap-chart-to-a-treemapseries-object.html[Bind a Treemap Chart to a TreeMapSeries Object]
* link:chart-binding-to-an-array.html[Binding to an Array]
* link:chart-binding-to-classes-derived-from-collectionbase.html[Binding to Classes Derived from CollectionBase]
* link:chart-binding-to-a-dataset-dataview-or-datatable.html[Binding to a DataSet, DataView, or DataTable]
* link:chart-binding-to-ibindinglist-or-ilist.html[Binding to IBindingList or IList]

ifdef::win-forms,win-forms-old[]
* link:chart-binding-to-windatasource.html[Binding to WinDataSource]

endif::win-forms,win-forms-old[]

* link:chart-binding-to-an-xml-file.html[Binding to an XML File (with schema)]